In [1]:
# Importing all the required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sb
from sklearn import preprocessing 
import warnings 
warnings.filterwarnings('ignore')

In [2]:
missing_values = ['-' , ' ' , '?' , 'Nan']
df = pd.read_csv('adult.csv', na_values = missing_values)

In [62]:
df.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18        NaN  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                NaN    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [63]:
df.isnull().sum()

age                   0
workclass          2799
fnlwgt                0
education             0
educational-num       0
marital-status        0
occupation         2809
relationship          0
race                  0
gender                0
capital-gain          0
capital-loss          0
hours-per-week        0
native-country      857
income                0
dtype: int64

In [64]:
df.isnull().sum().sum()

6465

In [3]:
df.dropna(how = 'any' , inplace = True)

In [66]:
df.isnull().sum().sum()

0

In [14]:
df.describe()

age        fnlwgt  educational-num  capital-gain  \
count  45222.000000  4.522200e+04     45222.000000  45222.000000   
mean      38.547941  1.897347e+05        10.118460   1101.430344   
std       13.217870  1.056392e+05         2.552881   7506.430084   
min       17.000000  1.349200e+04         1.000000      0.000000   
25%       28.000000  1.173882e+05         9.000000      0.000000   
50%       37.000000  1.783160e+05        10.000000      0.000000   
75%       47.000000  2.379260e+05        13.000000      0.000000   
max       90.000000  1.490400e+06        16.000000  99999.000000   

       capital-loss  hours-per-week  
count  45222.000000    45222.000000  
mean      88.595418       40.938017  
std      404.956092       12.007508  
min        0.000000        1.000000  
25%        0.000000       40.000000  
50%        0.000000       40.000000  
75%        0.000000       45.000000  
max     4356.000000       99.000000

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45222 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              45222 non-null  int64 
 1   workclass        45222 non-null  object
 2   fnlwgt           45222 non-null  int64 
 3   education        45222 non-null  object
 4   educational-num  45222 non-null  int64 
 5   marital-status   45222 non-null  object
 6   occupation       45222 non-null  object
 7   relationship     45222 non-null  object
 8   race             45222 non-null  object
 9   gender           45222 non-null  object
 10  capital-gain     45222 non-null  int64 
 11  capital-loss     45222 non-null  int64 
 12  hours-per-week   45222 non-null  int64 
 13  native-country   45222 non-null  object
 14  income           45222 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.5+ MB


In [4]:
df = df.drop(['fnlwgt' ,'capital-gain' , 'capital-loss'] , axis = 1)

In [68]:
df.head()

age  workclass     education  educational-num      marital-status  \
0   25    Private          11th                7       Never-married   
1   38    Private       HS-grad                9  Married-civ-spouse   
2   28  Local-gov    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  Some-college               10  Married-civ-spouse   
5   34    Private          10th                6       Never-married   

          occupation   relationship   race gender  hours-per-week  \
0  Machine-op-inspct      Own-child  Black   Male              40   
1    Farming-fishing        Husband  White   Male              50   
2    Protective-serv        Husband  White   Male              40   
3  Machine-op-inspct        Husband  Black   Male              40   
5      Other-service  Not-in-family  White   Male              30   

  native-country income  
0  United-States  <=50K  
1  United-States  <=50K  
2  United-States   >50K  
3  United-States   >50K  
5  United-States  <=50K

In [5]:
df_num = df.select_dtypes(include = ['int64'])

In [72]:
df_num.head()

age  educational-num  hours-per-week
0   25                7              40
1   38                9              50
2   28               12              40
3   44               10              40
5   34                6              30

In [6]:
df_cat = df.select_dtypes(include = ['object'])

In [75]:
df_cat.head()

workclass     education      marital-status         occupation  \
0    Private          11th       Never-married  Machine-op-inspct   
1    Private       HS-grad  Married-civ-spouse    Farming-fishing   
2  Local-gov    Assoc-acdm  Married-civ-spouse    Protective-serv   
3    Private  Some-college  Married-civ-spouse  Machine-op-inspct   
5    Private          10th       Never-married      Other-service   

    relationship   race gender native-country income  
0      Own-child  Black   Male  United-States  <=50K  
1        Husband  White   Male  United-States  <=50K  
2        Husband  White   Male  United-States   >50K  
3        Husband  Black   Male  United-States   >50K  
5  Not-in-family  White   Male  United-States  <=50K

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df_num = pd.DataFrame(scaler.fit_transform(df_num), columns = df_num.columns)


In [8]:
print(df_num.shape)
df_num.head()


(45222, 3)


age  educational-num  hours-per-week
0 -1.024983        -1.221559       -0.078120
1 -0.041455        -0.438122        0.754701
2 -0.798015         0.737034       -0.078120
3  0.412481        -0.046403       -0.078120
4 -0.344079        -1.613277       -0.910942

In [9]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(drop='first', sparse=False)
df_cat = pd.DataFrame(encoder.fit_transform(df_cat),columns=encoder.get_feature_names(df_cat.columns))

In [10]:
print(df_cat.shape)
df_cat.head()

(45222, 91)


workclass_Local-gov  workclass_Private  workclass_Self-emp-inc  \
0                  0.0                1.0                     0.0   
1                  0.0                1.0                     0.0   
2                  1.0                0.0                     0.0   
3                  0.0                1.0                     0.0   
4                  0.0                1.0                     0.0   

   workclass_Self-emp-not-inc  workclass_State-gov  workclass_Without-pay  \
0                         0.0                  0.0                    0.0   
1                         0.0                  0.0                    0.0   
2                         0.0                  0.0                    0.0   
3                         0.0                  0.0                    0.0   
4                         0.0                  0.0                    0.0   

   education_11th  education_12th  education_1st-4th  education_5th-6th  ...  \
0             1.0             0.0                0.0                0.0  ...   
1             0.0             0.0                0.0                0.0  ...   
2             0.0             0.0                0.0                0.0  ...   
3             0.0             0.0                0.0                0.0  ...   
4             0.0             0.0                0.0                0.0  ...   

   native-country_Puerto-Rico  native-country_Scotland  native-country_South  \
0                         0.0                      0.0                   0.0   
1                         0.0                      0.0                   0.0   
2                         0.0                      0.0                   0.0   
3                         0.0                      0.0                   0.0   
4                         0.0                      0.0                   0.0   

   native-country_Taiwan  native-country_Thailand  \
0                    0.0                      0.0   
1                    0.0                      0.0   
2                    0.0                      0.0   
3                    0.0                      0.0   
4                    0.0                      0.0   

   native-country_Trinadad&Tobago  native-country_United-States  \
0                             0.0                           1.0   
1                             0.0                           1.0   
2                             0.0                           1.0   
3                             0.0                           1.0   
4                             0.0                           1.0   

   native-country_Vietnam  native-country_Yugoslavia  income_>50K  
0                     0.0                        0.0          0.0  
1                     0.0                        0.0          0.0  
2                     0.0                        0.0          1.0  
3                     0.0                        0.0          1.0  
4                     0.0                        0.0          0.0  

[5 rows x 91 columns]

In [11]:
df = pd.concat([df_num , df_cat],axis = 1)

In [12]:
print(df.shape)
df.head()

(45222, 94)


age  educational-num  hours-per-week  workclass_Local-gov  \
0 -1.024983        -1.221559       -0.078120                  0.0   
1 -0.041455        -0.438122        0.754701                  0.0   
2 -0.798015         0.737034       -0.078120                  1.0   
3  0.412481        -0.046403       -0.078120                  0.0   
4 -0.344079        -1.613277       -0.910942                  0.0   

   workclass_Private  workclass_Self-emp-inc  workclass_Self-emp-not-inc  \
0                1.0                     0.0                         0.0   
1                1.0                     0.0                         0.0   
2                0.0                     0.0                         0.0   
3                1.0                     0.0                         0.0   
4                1.0                     0.0                         0.0   

   workclass_State-gov  workclass_Without-pay  education_11th  ...  \
0                  0.0                    0.0             1.0  ...   
1                  0.0                    0.0             0.0  ...   
2                  0.0                    0.0             0.0  ...   
3                  0.0                    0.0             0.0  ...   
4                  0.0                    0.0             0.0  ...   

   native-country_Puerto-Rico  native-country_Scotland  native-country_South  \
0                         0.0                      0.0                   0.0   
1                         0.0                      0.0                   0.0   
2                         0.0                      0.0                   0.0   
3                         0.0                      0.0                   0.0   
4                         0.0                      0.0                   0.0   

   native-country_Taiwan  native-country_Thailand  \
0                    0.0                      0.0   
1                    0.0                      0.0   
2                    0.0                      0.0   
3                    0.0                      0.0   
4                    0.0                      0.0   

   native-country_Trinadad&Tobago  native-country_United-States  \
0                             0.0                           1.0   
1                             0.0                           1.0   
2                             0.0                           1.0   
3                             0.0                           1.0   
4                             0.0                           1.0   

   native-country_Vietnam  native-country_Yugoslavia  income_>50K  
0                     0.0                        0.0          0.0  
1                     0.0                        0.0          0.0  
2                     0.0                        0.0          1.0  
3                     0.0                        0.0          1.0  
4                     0.0                        0.0          0.0  

[5 rows x 94 columns]

In [13]:
X = df
y = df.pop('income_>50K')

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 42)

In [57]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(31655, 93) (31655,)
(13567, 93) (13567,)


In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import cross_val_score

In [16]:
reg = LogisticRegression()
reg.fit(X_train , y_train)
y_train_predict = reg.predict(X_train)
y_test_predict = reg.predict(X_test)

In [17]:
print("Accuracy Score :",metrics.accuracy_score(y_test , y_test_predict))
print("Confusion metrics : \n", metrics.confusion_matrix(y_test,y_test_predict))
print("Recall : " , metrics.recall_score(y_test, y_test_predict))
print("Precision : ", metrics.precision_score(y_test, y_test_predict))

Accuracy Score : 0.8330507849929977
Confusion metrics : 
 [[9425  816]
 [1449 1877]]
Recall :  0.5643415514131088
Precision :  0.6969922020051986


In [18]:
print(metrics.classification_report(y_test, y_test_predict))
# Number of features = 94

              precision    recall  f1-score   support

         0.0       0.87      0.92      0.89     10241
         1.0       0.70      0.56      0.62      3326

    accuracy                           0.83     13567
   macro avg       0.78      0.74      0.76     13567
weighted avg       0.83      0.83      0.83     13567



# Feature Selection through PCA

In [19]:
from sklearn.decomposition import PCA
pca = PCA(random_state = 0)
pca.fit(X_train)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=0,
    svd_solver='auto', tol=0.0, whiten=False)

In [20]:
np.cumsum(pca.explained_variance_ratio_)

array([0.20950414, 0.37211014, 0.50555712, 0.56695676, 0.60585443,
       0.63977929, 0.67346229, 0.70063442, 0.72475608, 0.74801193,
       0.76824837, 0.78666188, 0.8040827 , 0.81918534, 0.83319157,
       0.84691954, 0.85920598, 0.87028056, 0.88001767, 0.8895197 ,
       0.89792479, 0.90578034, 0.91281272, 0.91933084, 0.92505526,
       0.93040321, 0.93571766, 0.94091728, 0.9460327 , 0.95053199,
       0.95493589, 0.95926571, 0.96320401, 0.96626942, 0.96929536,
       0.97219613, 0.97464788, 0.9767972 , 0.97887004, 0.98083743,
       0.98246426, 0.98405906, 0.98549799, 0.98681993, 0.98771731,
       0.98856432, 0.98935339, 0.99007806, 0.99068411, 0.9912502 ,
       0.99176729, 0.99224787, 0.99269525, 0.99309638, 0.99347984,
       0.99384169, 0.99419869, 0.99452361, 0.99484129, 0.99515553,
       0.99546413, 0.99576535, 0.99605353, 0.9963386 , 0.99661698,
       0.99688282, 0.99713003, 0.99736511, 0.9975876 , 0.99778282,
       0.99797116, 0.99814152, 0.99830445, 0.99846078, 0.99861

In [21]:
pca_final = PCA(n_components = 20, random_state = 41)

X_train_pca = pca_final.fit_transform(X_train)
X_test_pca = pca_final.transform(X_test)

### Logistic Regression

In [22]:
from sklearn.linear_model import LogisticRegression

reg_pca = LogisticRegression()

reg_pca.fit(X_train_pca, y_train)
y_test_predict_lr = reg_pca.predict(X_test_pca)

In [80]:
from sklearn import metrics
print("Logistic Regressionn :-")
print("Accuracy Score :",metrics.accuracy_score(y_test , y_test_predict_lr))
print("Confusion metrics : \n", metrics.confusion_matrix(y_test,y_test_predict_lr))
print("Recall : " , metrics.recall_score(y_test, y_test_predict_lr))
print("Precision : ", metrics.precision_score(y_test, y_test_predict_lr))

Logistic Regressionn :-
Accuracy Score : 0.830470995798629
Confusion metrics : 
 [[9457  784]
 [1516 1810]]
Recall :  0.5441972339146122
Precision :  0.6977640709329221


### K-NN

In [78]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier.fit(X_train_pca, y_train)
y_test_predict_knn = classifier.predict(X_test_pca)

In [82]:
print("K-NN :-")
print("Accuracy Score :",metrics.accuracy_score(y_test , y_test_predict_knn))
print("Confusion metrics : \n", metrics.confusion_matrix(y_test,y_test_predict_knn))
print("Recall : " , metrics.recall_score(y_test, y_test_predict_knn))
print("Precision : ", metrics.precision_score(y_test, y_test_predict_knn))

K-NN :-
Accuracy Score : 0.8131495540650107
Confusion metrics : 
 [[9099 1142]
 [1393 1933]]
Recall :  0.5811785929043897
Precision :  0.6286178861788618


### Decision Tree

In [83]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(max_depth = 100)
clf = clf.fit(X_train_pca , y_train)
y_test_predict_dt = clf.predict(X_test_pca)

In [84]:
print("Decision Tree :-")
print("Accuracy Score :",metrics.accuracy_score(y_test , y_test_predict_dt))
print("Confusion metrics : \n", metrics.confusion_matrix(y_test,y_test_predict_dt))
print("Recall : " , metrics.recall_score(y_test, y_test_predict_dt))
print("Precision : ", metrics.precision_score(y_test, y_test_predict_dt))

Decision Tree :-
Accuracy Score : 0.7758531731407091
Confusion metrics : 
 [[8848 1393]
 [1648 1678]]
Recall :  0.5045099218280217
Precision :  0.5464018235102572


### SVM 

In [23]:
from sklearn.svm import SVC
classifier_svc = SVC()
classifier_svc.fit(X_train_pca , y_train)
y_test_predict_svm = classifier_svc.predict(X_test_pca)

In [24]:
print("SVM :-")
print("Accuracy Score :",metrics.accuracy_score(y_test , y_test_predict_svm))
print("Confusion metrics : \n", metrics.confusion_matrix(y_test,y_test_predict_svm))
print("Recall : " , metrics.recall_score(y_test, y_test_predict_svm))
print("Precision : ", metrics.precision_score(y_test, y_test_predict_svm))

SVM :-
Accuracy Score : 0.8365887816024177
Confusion metrics : 
 [[9422  819]
 [1398 1928]]
Recall :  0.5796752856283824
Precision :  0.701856570804514


In [67]:
print(metrics.classification_report(y_test, y_test_predict))
# Number of features = 94

              precision    recall  f1-score   support

         0.0       0.87      0.92      0.89     10241
         1.0       0.70      0.56      0.62      3326

    accuracy                           0.83     13567
   macro avg       0.78      0.74      0.76     13567
weighted avg       0.83      0.83      0.83     13567



# Feature selection through RFE

In [40]:
df_train,df_test = train_test_split(df, train_size = 0.7, random_state = 42)

In [27]:
from sklearn.feature_selection import RFE

rfe = RFE(reg, 50)
rfe = rfe.fit(X_train, y_train)

In [28]:
temp_df = pd.DataFrame({'Columns' : X_train.columns, 'Included' : rfe.support_, 'Ranking' : rfe.ranking_})
temp_df

Columns  Included  Ranking
0                              age      True        1
1                  educational-num      True        1
2                   hours-per-week      True        1
3              workclass_Local-gov     False        7
4                workclass_Private     False        8
..                             ...       ...      ...
88         native-country_Thailand      True        1
89  native-country_Trinadad&Tobago      True        1
90    native-country_United-States     False       15
91          native-country_Vietnam      True        1
92       native-country_Yugoslavia      True        1

[93 rows x 3 columns]

In [29]:
imp_col = X_train.columns[rfe.support_]
imp_col

Index(['age', 'educational-num', 'hours-per-week',
       'workclass_Self-emp-not-inc', 'workclass_State-gov',
       'workclass_Without-pay', 'education_1st-4th', 'education_5th-6th',
       'education_Assoc-acdm', 'education_Prof-school',
       'marital-status_Married-AF-spouse', 'marital-status_Married-civ-spouse',
       'marital-status_Never-married', 'occupation_Exec-managerial',
       'occupation_Farming-fishing', 'occupation_Handlers-cleaners',
       'occupation_Machine-op-inspct', 'occupation_Other-service',
       'occupation_Priv-house-serv', 'occupation_Prof-specialty',
       'occupation_Tech-support', 'relationship_Other-relative',
       'relationship_Own-child', 'relationship_Wife',
       'race_Asian-Pac-Islander', 'race_Black', 'race_Other', 'race_White',
       'gender_Male', 'native-country_China', 'native-country_Columbia',
       'native-country_Dominican-Republic', 'native-country_Ecuador',
       'native-country_England', 'native-country_France',
       'nati

In [41]:
X_train_new = df_train[imp_col]
X_train_new.head()

age  educational-num  hours-per-week  workclass_Self-emp-not-inc  \
25947 -0.041455         1.520471        1.587523                         0.0   
39938  0.639449        -0.438122        0.338291                         0.0   
38364  0.336825         1.128753        0.754701                         0.0   
11567  0.261169         2.303909       -0.078120                         0.0   
7173  -0.949327        -0.438122       -0.078120                         0.0   

       workclass_State-gov  workclass_Without-pay  education_1st-4th  \
25947                  1.0                    0.0                0.0   
39938                  0.0                    0.0                0.0   
38364                  0.0                    0.0                0.0   
11567                  0.0                    0.0                0.0   
7173                   0.0                    0.0                0.0   

       education_5th-6th  education_Assoc-acdm  education_Prof-school  ...  \
25947                0.0                   0.0                    0.0  ...   
39938                0.0                   0.0                    0.0  ...   
38364                0.0                   0.0                    0.0  ...   
11567                0.0                   0.0                    0.0  ...   
7173                 0.0                   0.0                    0.0  ...   

       native-country_Nicaragua  native-country_Outlying-US(Guam-USVI-etc)  \
25947                       0.0                                        0.0   
39938                       0.0                                        0.0   
38364                       0.0                                        0.0   
11567                       0.0                                        0.0   
7173                        0.0                                        0.0   

       native-country_Peru  native-country_Portugal  native-country_Scotland  \
25947                  0.0                      0.0                      0.0   
39938                  0.0                      0.0                      0.0   
38364                  0.0                      0.0                      0.0   
11567                  0.0                      0.0                      0.0   
7173                   0.0                      0.0                      0.0   

       native-country_South  native-country_Thailand  \
25947                   0.0                      0.0   
39938                   0.0                      0.0   
38364                   0.0                      0.0   
11567                   1.0                      0.0   
7173                    0.0                      0.0   

       native-country_Trinadad&Tobago  native-country_Vietnam  \
25947                             0.0                     0.0   
39938                             0.0                     0.0   
38364                             0.0                     0.0   
11567                             0.0                     0.0   
7173                              0.0                     0.0   

       native-country_Yugoslavia  
25947                        0.0  
39938                        0.0  
38364                        0.0  
11567                        0.0  
7173                         0.0  

[5 rows x 50 columns]

In [43]:
regressor = LogisticRegression()
regressor.fit(X_train_new, y_train)
y_train_predict_new = regressor.predict(X_train_new)

In [45]:
X_test_new = df_test[imp_col]
y_test_predict_new = regressor.predict(X_test_new)

In [46]:
temp_df_new = pd.DataFrame({'Actual' : y_test , 'Predicted' : y_test_predict_new})
temp_df_new

Actual  Predicted
20084     0.0        0.0
20027     0.0        0.0
39505     1.0        1.0
39534     0.0        0.0
12586     0.0        0.0
...       ...        ...
34451     1.0        1.0
21928     0.0        0.0
18106     0.0        0.0
31496     0.0        0.0
37077     0.0        0.0

[13567 rows x 2 columns]

In [47]:
print("Accuracy Score :",metrics.accuracy_score(y_test , y_test_predict_new))
print("Confusion metrics : \n", metrics.confusion_matrix(y_test,y_test_predict_new))
print("Recall : " , metrics.recall_score(y_test, y_test_predict_new))
print("Precision : ", metrics.precision_score(y_test, y_test_predict_new))

Accuracy Score : 0.8326085354168202
Confusion metrics : 
 [[9445  796]
 [1475 1851]]
Recall :  0.5565243535778713
Precision :  0.6992822062712505
